### ISSUE TITLE
Release Plan - 0.1.5

### ISSUE THREAD

**Issue by ChakshuGautam** [BharatSahAIyak/.github#18]
### Inputs
- [x] PDF - 
- [x] Video - 1 Video relevant to the PDF and 1 Video irrelevant
- [x] XLSX - Default one

### Orchestration Testing
- [x] 1 Question only from PDF
- [x] 1 Question only from PDF + Video
- [x] 1 Question on irrelevant video
- [x] 1 Question only XLSX

### Ouputs
- [x] Results of Orchestration Testing @tanishk2907 
- [x] Demo Video of new features @tanishk2907 
- [ ] Changelog published on the website as well as on the main repo (@chinmoy12c)
- [ ] Documentation on new features that we added (@chinmoy12c)

**Comment by tanishk2907** [comment]
Dummy excel file (book club agenda) ; [Sheet2pdf test (1).xlsx](https://github.com/BharatSahAIyak/.github/files/14415163/Sheet2pdf.test.1.xlsx)

Pomodoro pdf- [Cirillo -- Pomodoro Technique.pdf](https://github.com/BharatSahAIyak/.github/files/14415162/Cirillo.--.Pomodoro.Technique.pdf)

relevant video to pomodoro- [https://www.youtube.com/watch?v=mNBmG24djoY&t=33s](url)

irrelevant video - [https://www.youtube.com/watch?v=dCy0vX0fJjQ](url) (budget highlights)

**Comment by tanishk2907** [comment]
1. excel - which sessions will be anchored by the block moderator?
2. Pomodoro pdf - What are the goals and assumptions of Pomodoro technique? 
3. Pomodoro YT+pdf- How to avoid distractions during a pomodoro cycle?
4. Budget YT- A what % is the fiscal deficit pegged to the GDP?

**Comment by ChakshuGautam** [comment]
- [ ] Changelog
- [ ] Documentation
- [ ] Demo

**Comment by tanishk2907** [comment]
YT test- https://drive.google.com/file/d/1khz1KJ4LYUYUtlDnw1P69kscZxjipI7L/view?usp=sharing

excel +pdf - https://drive.google.com/file/d/1i-MqgH5RB8KjhnGF2TmMmzC7EDYnk7Ot/view?usp=sharing

**Comment by chinmoy12c** [comment]
Release created: https://github.com/BharatSahAIyak/bharat-sahAIyak/releases/tag/v0.1.5
